name: Deploy to Pterodactyl

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Reinstall Pterodactyl Server
        run: |
          curl -X POST \
            "https://panel.spaceify.eu/api/client/servers/09da5fe8/reinstall" \
            -H "Authorization: Bearer ptlc_rLtMojOQSFGANviMxiLNC0SHhLxyTpehpLuEI9RZPLH" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json"